name: flutter_application_1
description: "Aplikasi Projek Flutter ."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.1
  google_fonts: ^4.0.1
  flutter_svg: ^2.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/POLBENG.png



#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: assets/fonts/Poppins-SemiBold.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

